server:
  port: ${SERVER_PORT:8080}

spring:
  threads:
    virtual:
      enabled: ${TOMCAT_VIRTUAL_THREADS_ENABLED:false}
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      database: ${REDIS_DATABASE:0}
      timeout: ${REDIS_TIMEOUT:2000}